language: csharp
mono: none
dotnet: 2.1

branches:  
  only:
    - master

script:
 - cd src/CompanionTown
 - dotnet restore
 - dotnet build -c Release
 - dotnet test Tests/Api.Tests/Api.Tests.csproj
